In [3]:
import pandas as pd
import numpy as np

In [5]:
dataset=pd.read_csv('/content/smart_mobility_dataset.csv')

In [6]:
dataset.shape

(5000, 15)

In [7]:
dataset.info()


<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 15 columns):
 #   Column                  Non-Null Count  Dtype  
---  ------                  --------------  -----  
 0   Timestamp               5000 non-null   object 
 1   Latitude                5000 non-null   float64
 2   Longitude               5000 non-null   float64
 3   Vehicle_Count           5000 non-null   int64  
 4   Traffic_Speed_kmh       5000 non-null   float64
 5   Road_Occupancy_%        5000 non-null   float64
 6   Traffic_Light_State     5000 non-null   object 
 7   Weather_Condition       5000 non-null   object 
 8   Accident_Report         5000 non-null   int64  
 9   Sentiment_Score         5000 non-null   float64
 10  Ride_Sharing_Demand     5000 non-null   int64  
 11  Parking_Availability    5000 non-null   int64  
 12  Emission_Levels_g_km    5000 non-null   float64
 13  Energy_Consumption_L_h  5000 non-null   float64
 14  Traffic_Condition       5000 non-null   

In [8]:
dataset.isnull().sum()

Timestamp                 0
Latitude                  0
Longitude                 0
Vehicle_Count             0
Traffic_Speed_kmh         0
Road_Occupancy_%          0
Traffic_Light_State       0
Weather_Condition         0
Accident_Report           0
Sentiment_Score           0
Ride_Sharing_Demand       0
Parking_Availability      0
Emission_Levels_g_km      0
Energy_Consumption_L_h    0
Traffic_Condition         0
dtype: int64

In [9]:
x=dataset.iloc[:,:-1]
y=dataset.iloc[:,-1]
print(f'data overall{x}')

print(f'\ntarget variable{y}')

data overall                Timestamp   Latitude  Longitude  Vehicle_Count  \
0     2024-03-01 00:00:00  40.842275 -73.703149            205   
1     2024-03-01 00:05:00  40.831119 -73.987354            202   
2     2024-03-01 00:10:00  40.819549 -73.732462            252   
3     2024-03-01 00:15:00  40.725849 -73.980134             37   
4     2024-03-01 00:20:00  40.813265 -73.961631             64   
...                   ...        ...        ...            ...   
4995  2024-03-18 08:15:00  40.604663 -73.831032            266   
4996  2024-03-18 08:20:00  40.733790 -73.752213             20   
4997  2024-03-18 08:25:00  40.821354 -73.759376             43   
4998  2024-03-18 08:30:00  40.772343 -73.836698             88   
4999  2024-03-18 08:35:00  40.756688 -73.849335            147   

      Traffic_Speed_kmh  Road_Occupancy_% Traffic_Light_State  \
0             49.893435         82.652780              Yellow   
1             22.383965         45.829298               Green   


In [10]:
x.info()


<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 14 columns):
 #   Column                  Non-Null Count  Dtype  
---  ------                  --------------  -----  
 0   Timestamp               5000 non-null   object 
 1   Latitude                5000 non-null   float64
 2   Longitude               5000 non-null   float64
 3   Vehicle_Count           5000 non-null   int64  
 4   Traffic_Speed_kmh       5000 non-null   float64
 5   Road_Occupancy_%        5000 non-null   float64
 6   Traffic_Light_State     5000 non-null   object 
 7   Weather_Condition       5000 non-null   object 
 8   Accident_Report         5000 non-null   int64  
 9   Sentiment_Score         5000 non-null   float64
 10  Ride_Sharing_Demand     5000 non-null   int64  
 11  Parking_Availability    5000 non-null   int64  
 12  Emission_Levels_g_km    5000 non-null   float64
 13  Energy_Consumption_L_h  5000 non-null   float64
dtypes: float64(7), int64(4), object(3)
memor

In [11]:
y



0         High
1         High
2         High
3         High
4          Low
         ...  
4995      High
4996       Low
4997    Medium
4998    Medium
4999    Medium
Name: Traffic_Condition, Length: 5000, dtype: object

In [12]:
obj=x.select_dtypes(include='object').columns
print(obj)

Index(['Timestamp', 'Traffic_Light_State', 'Weather_Condition'], dtype='object')


In [13]:
from sklearn.preprocessing import LabelEncoder


#Create a LabelEncoder instance
label_encoder=LabelEncoder()

#List of catagorical columns to encode
categorical_columns=obj

#loop through each categorical column and apply labelencoding
for col in categorical_columns:
  x[col]=label_encoder.fit_transform(x[col])

# Display the updated DataFrame
print("\nUpdated Features (x) after Label Encoding:")
print(x)


Updated Features (x) after Label Encoding:
      Timestamp   Latitude  Longitude  Vehicle_Count  Traffic_Speed_kmh  \
0             0  40.842275 -73.703149            205          49.893435   
1             1  40.831119 -73.987354            202          22.383965   
2             2  40.819549 -73.732462            252          46.889699   
3             3  40.725849 -73.980134             37           5.730536   
4             4  40.813265 -73.961631             64          61.348034   
...         ...        ...        ...            ...                ...   
4995       4995  40.604663 -73.831032            266          22.987611   
4996       4996  40.733790 -73.752213             20          75.736987   
4997       4997  40.821354 -73.759376             43          59.492981   
4998       4998  40.772343 -73.836698             88          25.901119   
4999       4999  40.756688 -73.849335            147          51.473769   

      Road_Occupancy_%  Traffic_Light_State  Weather_Co

In [14]:
y=label_encoder.fit_transform(y)
print(y)

[0 0 0 ... 2 2 2]


In [15]:
y

array([0, 0, 0, ..., 2, 2, 2])

In [16]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=0)

In [18]:
x_train

Timestamp   Latitude  Longitude  Vehicle_Count  Traffic_Speed_kmh  \
2913       2913  40.868416 -73.903258             62          55.115713   
3275       3275  40.732082 -73.781210            201          12.075718   
775         775  40.860667 -73.887343            192          13.650555   
217         217  40.653914 -73.755487            281          67.060290   
1245       1245  40.867202 -73.897207            176          34.786153   
...         ...        ...        ...            ...                ...   
4931       4931  40.733157 -73.888878            200           8.543130   
3264       3264  40.763381 -73.893354            129          26.967951   
1653       1653  40.683605 -73.734997            141          13.115319   
2607       2607  40.624668 -73.756131            229           8.813796   
2732       2732  40.818515 -73.783306             42          41.579635   

      Road_Occupancy_%  Traffic_Light_State  Weather_Condition  \
2913         14.999070                    2                  3   
3275         96.829206                    1                  2   
775          12.176909                    2                  1   
217          11.958625                    1                  1   
1245         46.523881                    0                  1   
...                ...                  ...                ...   
4931         42.733917                    2                  1   
3264         74.508766                    0                  3   
1653         78.496196                    0                  2   
2607         62.545265                    1                  1   
2732         20.122979                    2                  2   

      Accident_Report  Sentiment_Score  Ride_Sharing_Demand  \
2913                0        -0.020492                   97   
3275                0         0.775519                   26   
775                 0         0.820123                   94   
217                 0        -0.693719                   34   
1245                0        -0.922156                   72   
...               ...              ...                  ...   
4931                1         0.215771                   16   
3264                0        -0.811069                   67   
1653                0        -0.467976                   96   
2607                0         0.196386                   61   
2732                0        -0.878780                   83   

      Parking_Availability  Emission_Levels_g_km  Energy_Consumption_L_h  
2913                    28            476.861293               16.582302  
3275                    37            488.668594               27.024215  
775                      7            191.304237                8.975665  
217                      5            429.022104               18.983663  
1245                    41            363.221894                9.596966  
...                    ...                   ...                     ...  
4931                    44             50.821216               11.087312  
3264                    11            449.314729               29.981249  
1653                    28            484.820938               16.605865  
2607                    20            268.487817               29.448069  
2732                     4             57.847310               13.921890  

[4000 rows x 14 columns]

In [19]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
x_train_scaled=sc.fit_transform(x_train)
x_test_scaled=sc.transform(x_test)

In [20]:
x_train_scaled

array([[ 0.28897155,  1.39010293, -0.64650057, ...,  0.21950747,
         1.56011512, -0.1204873 ],
       [ 0.5401706 , -0.20705793,  0.76227703, ...,  0.83711349,
         1.65061241,  1.32706602],
       [-1.19462949,  1.29932134, -0.46279909, ..., -1.22157324,
        -0.62854227, -1.17498878],
       ...,
       [-0.5853677 , -0.77495863,  1.29570511, ...,  0.21950747,
         1.62112197, -0.1172208 ],
       [ 0.07663202, -1.46540424,  1.05175987, ..., -0.32947566,
        -0.03696728,  1.66308286],
       [ 0.16337202,  0.80550814,  0.73808785, ..., -1.42744192,
        -1.65142538, -0.489298  ]])

In [21]:
x_test_scaled

array([[-1.45623735, -1.63690613,  0.21111782, ..., -0.741213  ,
         0.61954419,  1.27482117],
       [ 0.92737799, -0.09768514,  1.39232855, ...,  0.35675326,
        -1.44606749, -1.3243025 ],
       [ 1.62337979,  0.50710758,  0.85153772, ..., -0.26085277,
        -1.68843798,  0.51822689],
       ...,
       [-1.18560853,  1.12761605,  0.34220049, ...,  0.7684906 ,
         0.35902264,  0.41347432],
       [-0.72484563, -1.14869526, -0.02051575, ..., -0.19222987,
        -0.74087561,  0.3998981 ],
       [ 0.5332314 , -1.59427172, -1.02166827, ...,  1.66058819,
         1.6376081 , -0.28630882]])

In [22]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score,classification_report

In [23]:
LogisticRegression_model=LogisticRegression(random_state=0)
LogisticRegression_model.fit(x_train_scaled,y_train)

LogisticRegression(random_state=0)

In [24]:
weather_prediction=LogisticRegression_model.predict(x_test_scaled)
print("LogisticRegresstion:")
print("Accuracy:",accuracy_score(y_test,weather_prediction))

LogisticRegresstion:
Accuracy: 0.793


In [27]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier


In [30]:
DecisionTreeClassifier_model=DecisionTreeClassifier(random_state=0)
DecisionTreeClassifier_model.fit(x_train_scaled,y_train)



DecisionTreeClassifier(random_state=0)

In [31]:
weather_prediction=DecisionTreeClassifier_model.predict(x_test_scaled)
print("DecisionTreeClassifier:")
print("Accuracy:",accuracy_score(y_test,weather_prediction))

DecisionTreeClassifier:
Accuracy: 0.999


In [32]:
RandomForestClassifier_model=RandomForestClassifier(random_state=0)
RandomForestClassifier_model.fit(x_train_scaled,y_train)

RandomForestClassifier(random_state=0)

In [34]:
weather_predict=RandomForestClassifier_model.predict(x_test_scaled)
print("RandomForestClassifier:")
print("Accuracy:",accuracy_score(y_test,weather_predict))


RandomForestClassifier:
Accuracy: 0.999
